modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
description='''
MustJS is a utility mod that integrates JavaScript scripts into KubeJS, adding functions for Create recipes, item and fluid handling in recipes, and much more...
'''
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"